name: 'Apercu - Prune'
description: 'Prune all preview databases not linked to opened pull request'
author: 'Celer'

inputs:
  debug:
    description: 'Enable debug logs'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - id: apercu_run
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        chmod +x ${{ github.action_path }}/apercu
        if [[ "${{ inputs.debug }}" == 'true' ]]; then
          ${{ github.action_path }}/apercu -d prune --github-repository ${{ github.repository }}
        else
          ${{ github.action_path }}/apercu prune --github-repository ${{ github.repository }}
        fi
